//! Clipboard implementations for the unix backend.
//!
//! `Osc52Clipboard` encodes copied text as an OSC-52 sequence, which the daemon
//! sends down the client connection so the *client's* local terminal populates
//! its clipboard — the right behavior for attach over SSH/tunnel. The
//! in-memory variant is for tests.

use std::sync::{Arc, Mutex};
use wmux_core::traits::Clipboard;

/// Produces OSC-52 set-clipboard sequences. The generated bytes are meant to be
/// written to the client's terminal stream.
pub struct Osc52Clipboard {
    last: Arc<Mutex<Option<Vec<u8>>>>,
}

impl Osc52Clipboard {
    pub fn new() -> Self {
        Self {
            last: Arc::new(Mutex::new(None)),
        }
    }

    /// The OSC-52 sequence for `text` (base64 of the UTF-8 bytes). Delegates to
    /// the canonical encoder in `wmux_core`.
    pub fn osc52_sequence(text: &str) -> Vec<u8> {
        wmux_core::copymode::osc52(text)
    }

    /// The most recent emitted sequence (for the daemon to flush to the client).
    pub fn take_pending(&self) -> Option<Vec<u8>> {
        self.last.lock().unwrap().take()
    }
}

impl Default for Osc52Clipboard {
    fn default() -> Self {
        Self::new()
    }
}

impl Clipboard for Osc52Clipboard {
    fn set_text(&mut self, text: &str) -> std::io::Result<()> {
        *self.last.lock().unwrap() = Some(Self::osc52_sequence(text));
        Ok(())
    }
}

/// In-memory clipboard for tests.
#[derive(Default)]
pub struct MemoryClipboard {
    pub text: Arc<Mutex<String>>,
}

impl Clipboard for MemoryClipboard {
    fn set_text(&mut self, text: &str) -> std::io::Result<()> {
        *self.text.lock().unwrap() = text.to_string();
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn osc52_wraps_base64() {
        let seq = Osc52Clipboard::osc52_sequence("hi");
        let s = String::from_utf8(seq).unwrap();
        assert_eq!(s, "\x1b]52;c;aGk=\x07");
    }

    #[test]
    fn clipboard_set_text_records_pending() {
        let mut cb = Osc52Clipboard::new();
        cb.set_text("copied").unwrap();
        let pending = cb.take_pending().unwrap();
        assert!(String::from_utf8(pending)
            .unwrap()
            .starts_with("\x1b]52;c;"));
        assert!(cb.take_pending().is_none(), "taken once");
    }
}
