//! Clipboard implementations for the unix backend.
//!
//! `Osc52Clipboard` encodes copied text as an OSC-52 sequence, which the daemon
//! sends down the client connection so the *client's* local terminal populates
//! its clipboard — the right behavior for attach over SSH/tunnel. The
//! in-memory variant is for tests.

use std::sync::{Arc, Mutex};
use wmux_core::traits::Clipboard;

/// Produces OSC-52 set-clipboard sequences. The generated bytes are meant to be
/// written to the client's terminal stream.
pub struct Osc52Clipboard {
    last: Arc<Mutex<Option<Vec<u8>>>>,
}

impl Osc52Clipboard {
    pub fn new() -> Self {
        Self {
            last: Arc::new(Mutex::new(None)),
        }
    }

    /// The OSC-52 sequence for `text` (base64 of the UTF-8 bytes).
    pub fn osc52_sequence(text: &str) -> Vec<u8> {
        let b64 = base64_encode(text.as_bytes());
        format!("\x1b]52;c;{b64}\x07").into_bytes()
    }

    /// The most recent emitted sequence (for the daemon to flush to the client).
    pub fn take_pending(&self) -> Option<Vec<u8>> {
        self.last.lock().unwrap().take()
    }
}

impl Default for Osc52Clipboard {
    fn default() -> Self {
        Self::new()
    }
}

impl Clipboard for Osc52Clipboard {
    fn set_text(&mut self, text: &str) -> std::io::Result<()> {
        *self.last.lock().unwrap() = Some(Self::osc52_sequence(text));
        Ok(())
    }
}

/// In-memory clipboard for tests.
#[derive(Default)]
pub struct MemoryClipboard {
    pub text: Arc<Mutex<String>>,
}

impl Clipboard for MemoryClipboard {
    fn set_text(&mut self, text: &str) -> std::io::Result<()> {
        *self.text.lock().unwrap() = text.to_string();
        Ok(())
    }
}

/// Minimal standard base64 encoder (avoids a dependency for one small use).
fn base64_encode(input: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(input.len().div_ceil(3) * 4);
    for chunk in input.chunks(3) {
        let b = [
            chunk[0],
            *chunk.get(1).unwrap_or(&0),
            *chunk.get(2).unwrap_or(&0),
        ];
        let n = ((b[0] as u32) << 16) | ((b[1] as u32) << 8) | (b[2] as u32);
        out.push(TABLE[((n >> 18) & 63) as usize] as char);
        out.push(TABLE[((n >> 12) & 63) as usize] as char);
        out.push(if chunk.len() > 1 {
            TABLE[((n >> 6) & 63) as usize] as char
        } else {
            '='
        });
        out.push(if chunk.len() > 2 {
            TABLE[(n & 63) as usize] as char
        } else {
            '='
        });
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn base64_known_vectors() {
        assert_eq!(base64_encode(b""), "");
        assert_eq!(base64_encode(b"f"), "Zg==");
        assert_eq!(base64_encode(b"fo"), "Zm8=");
        assert_eq!(base64_encode(b"foo"), "Zm9v");
        assert_eq!(base64_encode(b"hello"), "aGVsbG8=");
    }

    #[test]
    fn osc52_wraps_base64() {
        let seq = Osc52Clipboard::osc52_sequence("hi");
        let s = String::from_utf8(seq).unwrap();
        assert_eq!(s, "\x1b]52;c;aGk=\x07");
    }

    #[test]
    fn clipboard_set_text_records_pending() {
        let mut cb = Osc52Clipboard::new();
        cb.set_text("copied").unwrap();
        let pending = cb.take_pending().unwrap();
        assert!(String::from_utf8(pending).unwrap().starts_with("\x1b]52;c;"));
        assert!(cb.take_pending().is_none(), "taken once");
    }
}
