[workspace]
resolver = "2"
members = [
    "crates/lumux-core",
    "crates/lumux-backend-unix",
    "crates/lumux-backend-win",
    "crates/lumux-server",
    "crates/lumux",
]

[workspace.package]
version = "0.1.11"
edition = "2021"
license = "MIT"
repository = "https://github.com/hgaol/lumux"

[workspace.dependencies]
lumux-core = { path = "crates/lumux-core", version = "0.1.11" }
lumux-server = { path = "crates/lumux-server", version = "0.1.11" }
lumux-backend-unix = { path = "crates/lumux-backend-unix", version = "0.1.11" }
lumux-backend-win = { path = "crates/lumux-backend-win", version = "0.1.11" }

# async runtime
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time", "process"] }
async-trait = "0.1"

# pty + terminal emulation
portable-pty = "0.8"
termwiz = "0.22"

# serialization / protocol
serde = { version = "1", features = ["derive"] }
bincode = "1"
bytes = "1"

# cli / config
clap = { version = "4", features = ["derive"] }
toml = "0.8"

# diagnostics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
thiserror = "1"

[profile.release]
lto = true
strip = true
codegen-units = 1
